name: Docker build
on: 
  push:
    branches: [ main ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: isidorastanic/demo-devops
          tag: latest
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          cache: true
          cache_registry: aevea/cache
